### ISSUE TITLE
Maven Repo

### ISSUE THREAD

**Issue by sha-2** [dmulloy2/PacketWrapper#19]
This artifact isn't present in the [maven repo](http://repo.dmulloy2.net/)

**Comment by dmulloy2** [comment]
I can add it, but PacketWrapper is intended to be copy-pasted into your project, so people don't have to worry about another dependency.

**Comment by sha-2** [comment]
Yeah, but with maven you can shade it into your jar, so it's a way more comfortable than copying everything

**Comment by dmulloy2** [comment]
I guess, but unless you minimize the jar, you'll end up with a ton of extra classes.

**Comment by sha-2** [comment]
Yes. I know. But it would be really nice, because you uploaded it to your old repo as well…

**Comment by dmulloy2** [comment]
Deployed.
