### ISSUE TITLE
WrapperPlayClientBlockPlace has changed with the 1.9 update.

### ISSUE THREAD

**Issue by axynos** [dmulloy2/PacketWrapper#22]
Some values have changed with 1.9.
http://wiki.vg/Pre-release_protocol#Player_Block_Placement

**Comment by dmulloy2** [comment]
I'm going to update PacketWrapper once ProtocolLib is all done.

**Comment by axynos** [comment]
Ok, thanks. :)

**Comment by Algeseven** [comment]
Is there an approximative date?

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/PacketWrapper/commit/22b866872c91cb5c40d758c870a05a3f2b6c6879
