### ISSUE TITLE
Deploy PacketWrapper to the maven repo

### ISSUE THREAD

**Issue by MiniDigger** [dmulloy2/PacketWrapper#25]
The snapshot repo has only 1.8.7 in it:
http://repo.dmulloy2.net/content/repositories/snapshots/com/comphenix/packetwrapper/PacketWrapper/
and the release doesn't have it at all.

**Comment by dmulloy2** [comment]
Ah I have most of my projects set to auto deploy, forgot I didn't do that for PacketWrapper. Should be all good.
