### ISSUE TITLE
CustomPayload packet typo in javadoc

### ISSUE THREAD

**Issue by Photon-GitHub** [dmulloy2/PacketWrapper#37]
The javadoc and the real parameter are not fitting.
```
/** ...
* @param content - new payload content
 */
public void setContentsBuffer(ByteBuf contents) {...}
```

**Comment by Photon-GitHub** [comment]
Both valid for the Client and the Server packet.

**Comment by dmulloy2** [comment]
Yeah the JavaDocs are a bit lacking in PacketWrapper, but I'm not exactly sure what to do about it. I don't really feel like fixing them all manually

**Comment by Photon-GitHub** [comment]
Opened a pull request.
