### ISSUE TITLE
Maven Repo is Down

### ISSUE THREAD

**Issue by Ghostium** [dmulloy2/PacketWrapper#38]
![unbenannt](https://cloud.githubusercontent.com/assets/15706162/25134408/c6e262f6-244f-11e7-8664-bc62eeb8569d.PNG)

http://downforeveryoneorjustme.com/http://repo.dmulloy2.net

The maven repo is unreachable for me too, so I'm submitting the issue.

**Comment by dmulloy2** [comment]
https://twitter.com/dmulloy2/status/854481675895615489

**Comment by dmulloy2** [comment]
It's back up now :)
