### ISSUE TITLE
PacketWrapper for Minecraft 1.12

### ISSUE THREAD

**Issue by Ghostium** [dmulloy2/PacketWrapper#40]
Hey,
do you have any plans for the 1.12 version? I'm looking forward to make use of the new advancements in 1.12 with packets.

**Comment by Ozek-HybridMC** [comment]
You can create the classes yourself really. Wrappit (script to make packetWrapper) is available to all, but it would be definitely nice if dmulloy2 could do it himself, and publish it to his repo 👍

**Comment by dmulloy2** [comment]
It's a good bit of the way done. I decided to design a system for dynamically creating wrappers for things like advancements instead of huge individual classes in ProtocolLib which ended up taking a long time.

**Comment by Ozek-HybridMC** [comment]
You sir are a God! I fully respect your work, and you are definitely a big part of the history of MC modding and plugin development.

**Comment by dmulloy2** [comment]
I wouldn't go that far, but thanks for the support haha
