### ISSUE TITLE
Missing Function

### ISSUE THREAD

**Issue by DrProfesor** [dmulloy2/PacketWrapper#44]
PacketContainer.getMinecraftKeys() does not exist anywhere? But it is used in the WrapperPlayServerSelectAdvancementTab

**Comment by games647** [comment]
Check if you are using the correct version of ProtocolLib, because it actually exists:

https://github.com/dmulloy2/ProtocolLib/blob/01b68cf8e5a5cf22cd178735d6879f17a054602e/modules/API/src/main/java/com/comphenix/protocol/events/PacketContainer.java#L920-L923
