### ISSUE TITLE
AbstractPacket: Typo in exception

### ISSUE THREAD

**Issue by Photon-GitHub** [dmulloy2/PacketWrapper#45]
`    public void receivePacket(Player sender)
    {
        try
        {
            ProtocolLibrary.getProtocolManager().recieveClientPacket(sender,
                                                                     getHandle());
        } catch (Exception e)
        {
            throw new RuntimeException("Cannot recieve packet.", e);
        }
    }`
The exception message should be 
`"Cannot receive packet."`
Probably copied over from the deprecated and misspelled method.

**Comment by dmulloy2** [comment]
You could pull request it

**Comment by Photon-GitHub** [comment]
Opened a pull request.
