### ISSUE TITLE
Update to 1.14

### ISSUE THREAD

**Issue by Joeywp** [dmulloy2/PacketWrapper#63]
1.14 has several new packets, such as open book several other field changes/removals/additions. Tried to figure out how wrappit works to generate the update myself, but couldn't really figure out how it works.

**Comment by DarkShimy00** [comment]
+1

**Comment by Joeywp** [comment]
Looks like the Protocol specs for 1.14 are also finally on the protocol wiki:
https://wiki.vg/Protocol

**Comment by joshaprior** [comment]
We really want this to happen

**Comment by Joeywp** [comment]
I think it would also be useful if @dmulloy2 could explain on how to properly use wrappit (if thats still the used tool for it), so maybe the community could help with this work?

**Comment by Tofuus** [comment]
I've put a little bit of work towards getting Wrappit working for 1.14. You can find my repo over [here](https://github.com/Lord-of-the-Craft/Wrappit). 

If you want to contribute you basically build Wrappit, run it, then look at the errors and figure out what modifiers you haven't mapped yet. There's a couple things that look like they don't have a corresponding method in Protocollib so they can't be mapped at all.

**Comment by LoneDev6** [comment]
Any news on this?

**Comment by dmulloy2** [comment]
@Joeywp I still don't completely understand wrappit. I didn't write it, the previous author of PL did.

@Tofuus Wrappit is somewhat good at generating new wrappers, but the bulk of the work in updating PacketWrapper is going packet-by-packet and updating it based on the wiki changes.

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/PacketWrapper/commit/5262e36c72b66a6b94eb97edc710094329a3ce5e
