### ISSUE TITLE
Unnecessary Changes in 1.8

### ISSUE THREAD

**Issue by SupaHam** [dmulloy2/PacketWrapper#8]
I appreciate you guys updating this and all, but is breaking almost every single method reaaally necessary? You shouldn't have removed comphenix's implementations and instead append your own. A ton of code from an old plugin I wrote is broken because of your changes. This is not how you're supposed to do things. I'm still lost trying to find the proper methods for each of my old features... But thats not the point, take this as a lesson and not repeat your actions. [Have a look at the deprecate annotation provided by the JDK](http://docs.oracle.com/javase/8/docs/technotes/guides/javadoc/deprecation/deprecation.html)

**Comment by dmulloy2** [comment]
Oh gee, thanks mister! I had no idea there was a deprecation annotation, [it's not like I've used it before or anything](https://github.com/dmulloy2/ProtocolLib/commit/1f6b873f846fd3599005480c1cb0cca3fa9205a9).

PacketWrapper is generated almost completely by a [script](https://github.com/aadnk/Wrappit) because honestly I don't have the time or will to create 50+ wrappers.  If you do, you're more than welcome to do so.

I reaaally don't appreciate your condescending attitude.  This is a FREE tool.  I allow anyone to use it free of charge.  I don't work for you and I'm under no obligation to make sure your precious old features still work.  If you want someone to fix something for you, the absolute worst way to go about it is to be condescending.

Also, thanks for providing examples, it really helps.

**Comment by SupaHam** [comment]
"Condescending attitude"? Where the fuck was I being condescending, you clearly are taking a greater offence than you should ever. I'm taking the time out of my day to give you a fucking lesson on how you're supposed to not break shit, but instead you tell me that you do infact know that such an annotation exist, yet you fail to fucking utilize it. 

I don't know anything about Wrappit, but either you're using it wrong, or it's most likely not up to date. You know, I'd bother helping you, but since you're being such a fucking bitch, you can pretty much keep this shit broken until other people come along and complain about how your 1.8 update broke their shit.

I don't even know which example to provide out of probably like 50-80% of the changes in a7dd0de... just have a look for yourself, you're renaming methods for no reason, at least not one that I can justify by myself.

**Comment by mbax** [comment]
https://github.com/dmulloy2/PacketWrapper/issues/8#issuecomment-87270840
>
>Oh gee, thanks mister! I had no idea there was a deprecation annotation, it's not like I've used it before or anything.
>
>PacketWrapper is generated almost completely by a script because honestly I don't have the time or will to create 50+ wrappers. If you do, you're more than welcome to do so.
>
>I reaaally don't appreciate your condescending attitude. This is a FREE tool. I allow anyone to use it free of charge. I don't work for you and I'm under no obligation to make sure your precious old features still work. If you want someone to fix something for you, the absolute worst way to go about it is to be condescending.
>
>Also, thanks for providing examples, it really helps.


That's an extremely rude response to a frustrated user. :crying_cat_face:

**Comment by SupaHam** [comment]
Sorry for any offense you may have taken from my intentionally educational comment: Which example would you prefer I point out from a7dd0de. I fail to find any justifcation for you renaming methods such as getProfile() to getName, or setProfile(WrappedGameProfile) to setUuid(WrappedGameProfile) (which btw doesnt even make sense).

**Comment by kashike** [comment]
I don't see why you puposefully renamed classes and methods, breaking any existing code, when the names they had were fine.

Examples:

[1:]()
from `com.comphenix.packetwrapper.WrapperHandshakeClientSetProtocol` to `com.comphenix.packetwrapper.WrapperHandshakingClientSetProtocol`

[2:](https://github.com/dmulloy2/PacketWrapper/commit/db8496b8634b8d79952bf655f29f420f285a29e4#diff-4487fd4f5c6c8740cbb964bb365cbea3L1) Removing license headers.

[3:](https://github.com/dmulloy2/PacketWrapper/commit/db8496b8634b8d79952bf655f29f420f285a29e4#diff-8f3230c2337fb4353b812bb30f6577b9L43) from `public void setEntityID(int value)` to`public void setEntityId(int value)`

[4:](https://github.com/dmulloy2/PacketWrapper/commit/db8496b8634b8d79952bf655f29f420f285a29e4#diff-5d95f9c7b7725f0250a484f48304f863L23) from `public WrappedChatComponent getMessage()` to `public WrappedChatComponent getJsonData()`

I could go on and on lising unnecessary changes, but I'm sure you get the point.

**Comment by dmulloy2** [comment]
@kashike
PacketWrapper is almost completely generated by the script, [Wrappit](https://github.com/aadnk/Wrappit).  Wrappit was originally created by aadnk, and I updated it to 1.8.  The concept behind Wrappit is fairly simple: it pulls method names from the [wiki](http://wiki.vg/Protocol) and matches them up with the packet fields.  In practice, however, it can result in some awkward method names and casing.

I took over for aadnk just before the 1.8 update.  He was very helpful and provided me with Wrappit, but I hadn't planned on updating PacketWrapper.  After the update, [many people asked me to update PacketWrapper](https://github.com/dmulloy2/ProtocolLib/issues/4), so I figured I'd give it a shot.  Considering all of the issues regarding packet changes in 1.8, I decided the best course of action would be to completely regenerate the wrappers and fix any problems on a case-by-case basis.  This system worked very well up until now.

I'm willing to fix unnecessary changes and merge pull requests reverting said changes.

**Comment by kashike** [comment]
@dmulloy2 Perhaps you should read the [GNU Lesser General Public License v3.0 license](http://choosealicense.com/licenses/lgpl-3.0/) first. I'm sure after you read it you'll see what needs to be re-added.

**Comment by ams2990** [comment]
You removed many getEntity methods. Please re-add them.

**Comment by kashike** [comment]
Cheers, @dmulloy2.
