### ISSUE TITLE
Wrong setType and setEntityID not working...

### ISSUE THREAD

**Issue by ItzAmirreza** [dmulloy2/PacketWrapper#80]
Although your `WrapperPlayServerSpawnEntityLiving` doesn't support 1.16.4, I tried using them for my plugin and everything works fine but setType doesn't work correctly. For instance, I tried doing packet.setType(EntityType.ARMOR_STAND) and it spawned a giant, or I tried EntityType.BLAZE and it spawned a baby piglin. I noticed that setType is deprecated so something might be wrong with it with 1.16 so I decided to use setEntityID for setting my entity type. tried ids 1, 78, and 30 and none of them spawned anything. 

Wonder if it is an issue to get solved or if not/ how may I solve this problem. 

Thanks in advance.

Edit:

Protocollib version: 4.6.0, and the latest class of `WrapperPlayServerSpawnEntityLiving` is used. Minecraft Server Version that I'm testing in: 1.16.4

**Comment by Janmm14** [comment]
The getEntityID and setEntityID methods set the unique id of the specific entity and not its entity type.

Also getType and setType are not deprecated in WrapperPlayServerSpawnEntityLiving

**Comment by Janmm14** [comment]
why do you close this without any further comment
