### ISSUE TITLE
WrapperPlayServerWindowItems Error

### ISSUE THREAD

**Issue by MatzHilven** [dmulloy2/PacketWrapper#81]
It might be because I'm using  1.8, but I got an error when trying to get/set slot data. I fixed it by using 
```java
public ItemStack[] getSlotData() {
  return handle.getItemArrayModifier().read(0);
}
``` 
Instead of 
```java
public List<ItemStack> getSlotData() {
  return handle.getItemListModifier().read(0);
}
``` 
Since the packet `PacketOutPlayWindowItems` has an array as a field instead of a list.

**Comment by Joeywp** [comment]
You should probably use the latest 1.8 commit of this repository, which if I'm correct is this commit:
https://github.com/dmulloy2/PacketWrapper/tree/ecb89c0d97430d36017e4b1a888e6c8d0b41222b

Packets change every so often and this repository only hosts the latest versions

**Comment by MatzHilven** [comment]
Indeed, the old version had the correct methods.
